version: '3'

services:
  
  client:
    build: client/
    restart: always
    ports:
      - "3000:3000"

  server:
    build: server/
    restart: always
    ports:
      - "4000:4000"
    depends_on: 
      - mysql
    
  mysql:
    image: mysql:8
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
