version: '3'

services:
  
  client:
    build: client/
    ports:
      - "3000:3000"

  server:
    build: server/
    ports:
      - "4000:4000"
    depends_on: 
      - db
    
  db:
    image: mysql:latest
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "test"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    depends_on:
     - db
    ports:
     - 8888:80
